name: Main

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: send success telegram message
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            ✅  ${{ github.actor }} created commit:  
            
            📝  Commit message: ```${{ github.event.commits[0].message }} ``` 
            
            
            🌐 See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

      - name: send failure telegram message
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            ❌ ${{ github.actor }} created commit:  
            
            📝 Commit message: ${{ github.event.commits[0].message }}  
            
            
            🌐 See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}